#release configuration
#Wed Aug 12 15:06:13 CEST 2026
completedPhase=end-release
exec.additionalArguments=-Dmaven.test.skip\=true
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.retail.application\:application=0.0.2-SNAPSHOT
project.dev.com.retail.compositionroot\:catalogue-service=0.0.2-SNAPSHOT
project.dev.com.retail.core\:core=0.0.2-SNAPSHOT
project.dev.com.retail.domain\:domain=0.0.2-SNAPSHOT
project.dev.com.retail.infrastructure.persistence\:persistence-adapter=0.0.2-SNAPSHOT
project.dev.com.retail.infrastructure.web\:web-adapter=0.0.2-SNAPSHOT
project.dev.com.retail.infrastructure\:infrastructure=0.0.2-SNAPSHOT
project.dev.com.retail\:catalogue-service=0.0.2-SNAPSHOT
project.dev.com.retail\:domain-test-support=0.0.2-SNAPSHOT
project.rel.com.retail.application\:application=0.0.1
project.rel.com.retail.compositionroot\:catalogue-service=0.0.1
project.rel.com.retail.core\:core=0.0.1
project.rel.com.retail.domain\:domain=0.0.1
project.rel.com.retail.infrastructure.persistence\:persistence-adapter=0.0.1
project.rel.com.retail.infrastructure.web\:web-adapter=0.0.1
project.rel.com.retail.infrastructure\:infrastructure=0.0.1
project.rel.com.retail\:catalogue-service=0.0.1
project.rel.com.retail\:domain-test-support=0.0.1
project.scm.com.retail\:catalogue-service.connection=scm\:git\:git@github.com\:smgueye/hexagonal-starter.git
project.scm.com.retail\:catalogue-service.developerConnection=scm\:git\:git@github.com\:smgueye/hexagonal-starter.git
project.scm.com.retail\:catalogue-service.tag=HEAD
project.scm.com.retail\:catalogue-service.url=https\://github.com/smgueye/hexagonal-starter.git
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v0.0.1
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:git@github.com\:smgueye/hexagonal-starter.git
