management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always
      group:
        readiness:
          include:
            - readinessState
            - db
