spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      pool-name: postgres-catalogue-service
      maximum-pool-size: ${DB_MAX_POOL_SIZE}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}

  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: validate
      hibernate:
        jdbc:
          time_zone=UTC
    open-in-view: false

  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log:
      classpath:db/changelog/db.changelog-master.xml
