spring:
  application:
    name: catalogue-service

  config:
    import:
      - classpath:persistence-adapter.yaml
      - classpath:web-adapter.yaml

# Log structurée en JSON. Observabilité.04.
logging:
  structured:
    format:
      # console: ecs
      file: ecs
  file:
    name: ${LOG_FILE_PATH:logs/catalogue-service.log}

management:
  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${TRACE_HOST:http://localhost:4318}/v1/traces

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true