spring:
  application:
    name: catalogue-service

  config:
    import:
      - classpath:persistence-adapter.yaml
      - classpath:web-adapter.yaml

logging:
  structured:
    format:
      console: ecs
      file: ecs

management:
  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${TRACE_HOST}/v1/traces

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
